### ISSUE TITLE
error with python3

### ISSUE THREAD

**Issue by hjz95** [votchallenge/trax#47]
```
@@TRAX:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=2" "trax.channels=color;" 
@@TRAX:initialize "file:///home/space/Documents/GitHub/vot-toolkit-7.0.1/VOT19/sequences/boat/color/00000001.jpg" "592.0000,468.0000,167.0000,98.0000" 
@@TRAX:state "592.0000,468.0000,167.0000,98.0000" 
@@TRAX:frame "file:///home/space/Documents/GitHub/vot-toolkit-7.0.1/VOT19/sequences/boat/color/00000002.jpg" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/space/Documents/GitHub/pytracking/Test_VOT.py", line 58, in <module>
    handle.report(vot.Rectangle(360.9900,325.1100,25.7140,111.7600), 0.86)
  File "/home/space/Documents/GitHub/pytracking/vot.py", line 86, in report
    self._trax.status(tregion, properties)
  File "/home/space/Documents/GitHub/vot-toolkit-7.0.1/native/trax/support/python/trax/server.py", line 102, in status
    tproperties = Properties(properties)
  File "/home/space/Documents/GitHub/vot-toolkit-7.0.1/native/trax/support/python/trax/__init__.py", line 46, in __init__
    trax_properties_set(self._ref.reference(), key, str(value))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
@@TRAX:quit 
```
python2 tracker dose not have this problem.

**Comment by tangjiuqi097** [comment]
I also meet this issue. Have you solve it?

**Comment by Candice2Gao** [comment]
change 
trax_properties_set(self._ref.reference(), key, str(value))
to 
trax_properties_set(self._ref.reference(), bytes(key, encoding='utf-8'), bytes(str(value), encoding='utf-8'))
