### ISSUE TITLE
How can i complie opencv module

### ISSUE THREAD

**Issue by kuiran** [votchallenge/trax#61]
If you want to build optional OpenCV support, you will have to install OpenCV library (together with development header files). Depending on your OpenCV installation location you may have to tell the CMake where to find the library.

how can i install opencv library?Thank you.

**Comment by lukacu** [comment]
Installing OpenCV is really not in the scope of this project. There are many tutorials online that deal with this depending on your operating system.

**Comment by kuiran** [comment]
Traceback (most recent call last):
File "", line 1, in
File "/home/kuiran/github/pytracking/pytracking/run_vot.py", line 19, in run_vot
tracker.run_vot()
File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/tracker.py", line 621, in run_vot
handle = vot.VOT("polygon")
File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 92, in init
options = trax.server.ServerOptions(region_format, trax.image.PATH)
AttributeError: module 'trax.server' has no attribute 'ServerOptions'
Exception ignored in: <function VOT.del at 0x7fb0daca39e0>
Traceback (most recent call last):
File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 173, in del
self.quit()
File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 165, in quit
self._trax.quit()
AttributeError: 'VOT' object has no attribute '_trax'

use vot-toolkit to eval pytracking on vot 
the problem seems AttributeError: module 'trax.server' has no attribute 'ServerOptions'

how to fix it.
thank you

**Comment by lukacu** [comment]
From file paths I would assume that the problem is with vot.py wrapper provided with pytracking. So please open an issue there, they should probably update the wrapper.
