### ISSUE TITLE
need help!  AttributeError: module 'trax.server' has no attribute 'ServerOptions'

### ISSUE THREAD

**Issue by kuiran** [votchallenge/trax#62]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kuiran/github/pytracking/pytracking/run_vot.py", line 19, in run_vot
    tracker.run_vot()
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/tracker.py", line 621, in run_vot
    handle = vot.VOT("polygon")
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 92, in __init__
    options = trax.server.ServerOptions(region_format, trax.image.PATH)
AttributeError: module 'trax.server' has no attribute 'ServerOptions'
Exception ignored in: <function VOT.__del__ at 0x7fb0daca39e0>
Traceback (most recent call last):
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 173, in __del__
    self.quit()
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 165, in quit
    self._trax.quit()
AttributeError: 'VOT' object has no attribute '_trax'

how to fix it.

**Comment by laisimiao** [comment]
Me too! HELP!!

**Comment by laisimiao** [comment]
@lukacu How to solve this?

**Comment by yzlicloud** [comment]
me too

**Comment by lukacu** [comment]
My guess is that you are using an outdated pytracking vot module that uses an old API. Try replacing vot.py with a new one from our integration repository.

**Comment by zhanggtong** [comment]
> My guess is that you are using an outdated pytracking vot module that uses an old API. Try replacing vot.py with a new one from our integration repository.

Thank you very much,it works
