### ISSUE TITLE
trax.TraxException: Unable to connect to tracker

### ISSUE THREAD

**Issue by hongsheng-Z** [votchallenge/trax#65]
Hello, I encountered the following error, how should I solve it：
Traceback (most recent call last):
  File "/home/UserDirectory/hongshengz/anaconda3/envs/stark/lib/python3.8/site-packages/vot/tracker/trax.py", line 422, in initialize
    self._connect()
  File "/home/UserDirectory/hongshengz/anaconda3/envs/stark/lib/python3.8/site-packages/vot/tracker/trax.py", line 376, in _connect
    self._process = TrackerProcess(self._command, self._envvars, log=log, socket=self._socket, timeout=self._timeout)
  File "/home/UserDirectory/hongshengz/anaconda3/envs/stark/lib/python3.8/site-packages/vot/tracker/trax.py", line 194, in __init__
    raise e
  File "/home/UserDirectory/hongshengz/anaconda3/envs/stark/lib/python3.8/site-packages/vot/tracker/trax.py", line 188, in __init__
    self._client = Client(
  File "/home/UserDirectory/hongshengz/anaconda3/envs/stark/lib/python3.8/site-packages/trax/client.py", line 81, in __init__
    raise TraxException("Unable to connect to tracker")
**trax.TraxException: Unable to connect to tracker**

**Comment by lukacu** [comment]
This is a typical tracker startup problem, there is something wrong with tracker startup and the connection was terminated. Did you get some sort log?

**Comment by MinyueDayuan** [comment]
I met the same problem, could you tell me how to solve it?thanks a lot!

**Comment by hongsheng-Z** [comment]
> I met the same problem, could you tell me how to solve it?thanks a lot!

Yes, I have addressed this problem now! Maybe you can find the answer by this [link](https://blog.csdn.net/weixin_40367515/article/details/123818030?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522170124947616800225581080%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=170124947616800225581080&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-123818030-null-null.142^v96^pc_search_result_base1&utm_term=%E4%BD%BF%E7%94%A8vot-toolkit-python%E6%B5%8B%E8%AF%95VOT2020&spm=1018.2226.3001.4187), hope useful！
